name: cloudrun-deploy
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.DEPLOY_TOKEN }}

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/x-labs-313805/tadone-backend-services:latest
        gcloud config set run/region me-west1
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud run deploy tadone-backend-services --image gcr.io/x-labs-313805/tadone-backend-services:latest --region europe-west3 --platform managed --allow-unauthenticated --memory 512M
